<?php
/**
 * Copyright © TradeTracker. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var TradeTracker\Connect\Block\Adminhtml\System\Config\Button\Credentials $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<button type="button" id="tt-button_credentials" class="mm-acc-btn mm-acc-btn--outline">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75m-3-7.036A11.959 11.959 0 0 1 3.598 6 11.99 11.99 0 0 0 3 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285Z"/>
    </svg>
    <span><?= $escaper->escapeHtml(__('Check Credentials')); ?></span>
</button>
<div id="result_api">
    <span class="connecting" style="display: none;"><?= $escaper->escapeHtml(__('Connecting...')); ?></span>
    <span class="result"></span>
</div>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('#result_api');
        jQuery('#tt-button_credentials').click(function () {
            var params = {
                "customer_id": jQuery("input[name='groups[general][fields][customer_id][value]']").val(),
                "passphrase": jQuery("input[name='groups[general][fields][passphrase][value]']").val(),
                "sandbox": 0,
                "demo": 0,
            };
            new Ajax.Request('<?= $escaper->escapeUrl($block->getApiCheckUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find('.connecting').hide();
                    resultSpan.find('.result').show();
                    resultSpan.find('.result').html(response.responseJSON.result);
                }
            });
        });
    });
</script>
