<?php
/**
 * Copyright © TradeTracker. All rights reserved.
 * See COPYING.txt for license details.
 */

use TradeTracker\Connect\Block\Adminhtml\System\Config\Button\Credentials;

/**
 * @see Credentials
 * @var Credentials $block
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('#result_api');
        jQuery('#tt-button_credentials').click(function () {
            var params = {
                "customer_id": jQuery("input[name='groups[general][fields][customer_id][value]']").val(),
                "passphrase": jQuery("input[name='groups[general][fields][passphrase][value]']").val(),
                "sandbox": 0,
                "demo": 0,
            };
            new Ajax.Request('<?= $block->escapeUrl($block->getApiCheckUrl()) ?>', {
                parameters: params,
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    resultSpan.find('.connecting').hide();
                    resultSpan.find('.result').show();
                    resultSpan.find('.result').html(response.responseJSON.result);
                }
            });
        });
    });
</script>
<?= $block->getButtonHtml() ?>
<div id="result_api">
    <span class="connecting" style="display: none;">Connecting...</span>
    <span class="result"></span>
</div>
