<?php
/**
 * Copyright © TradeTracker. All rights reserved.
 * See COPYING.txt for license details.
 */

use TradeTracker\Connect\Block\Adminhtml\System\Config\Button\DebugCheck;

/**
 * @see \TradeTracker\Connect\Block\Adminhtml\System\Config\Button\DebugCheck
 * @var DebugCheck $block
 */
?>
<div id="tradetracker-result_debug-modal"
     data-tradetracker-endpoind-url="<?= $block->escapeUrl($block->getDebugCheckUrl()) ?>">
    <div id="tradetracker-result_debug">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>

