<?php
/**
 * Copyright © TradeTracker. All rights reserved.
 * See COPYING.txt for license details.
 */

use TradeTracker\Connect\Block\Adminhtml\System\Config\Button\ErrorCheck;

/**
 * @see \TradeTracker\Connect\Block\Adminhtml\System\Config\Button\ErrorCheck
 * @var ErrorCheck $block
 */
?>
<div id="mm-tradetracker-result_error-modal"
     data-mm-tradetracker-endpoind-url="<?= $block->escapeUrl($block->getErrorCheckUrl()) ?>">
    <div id="mm-tradetracker-result_error">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>
