<?php
/**
 * Copyright © TradeTracker. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var TradeTracker\Connect\Block\Adminhtml\System\Config\Button\Log $block
 */

/** @var \Magento\Framework\Escaper $escaper */
$escaper = $block->getEscaper();
?>
<div class="tradetracker-debug-button-wrapper">
    <div id="tradetracker-result_debug-modal"
         data-tradetracker-endpoind-url="<?= $escaper->escapeUrl($block->getDownloadUrl('debug')) ?>">
        <div id="tradetracker-result_debug">
            <div class="result"></div>
        </div>
    </div>
    <button type="button" id="tradetracker-button_debug" class="mm-acc-btn mm-acc-btn--outline">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 5.25h.008v.008H12v-.008Z"/>
        </svg>
        <span><?= $escaper->escapeHtml(__('Show last 100 debug log records')); ?></span>
    </button>
    <div id="tradetracker-result_error-modal"
         data-tradetracker-endpoind-url="<?= $escaper->escapeUrl($block->getDownloadUrl('error')) ?>">
        <div id="tradetracker-result_error">
            <div class="result"></div>
        </div>
    </div>
    <button type="button" id="tradetracker-button_error" class="mm-acc-btn mm-acc-btn--outline">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126ZM12 15.75h.007v.008H12v-.008Z"/>
        </svg>
        <span><?= $escaper->escapeHtml(__('Show last 100 error log records')); ?></span>
    </button>
</div>
