<?php
/**
 * Copyright © TradeTracker. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block TradeTracker\Connect\Block\Adminhtml\System\Config\Form\Field\Header
 */
?>
<div class="tradetracker-header">
    <p class="tradetracker-header-text">
        <?php $img = $block->getViewFileUrl('TradeTracker_Connect::images/tradetracker-logo-xs.svg'); ?>
        <img src="<?= $block->escapeUrl($img); ?>"/>
        <strong>TradeTracker extension for Magento 2.</strong><br>
        Directly connect your Magento e-commerce platform to TradeTracker and have fully functional tracking for your
        performance marketing programme. Provide the product feed URL so publishers can promote your products with up to
        date stock information.<br>
        <a href="https://merchant.tradetracker.com/portal/advertiserBrochure?loc=en_GB" target="_blank">
            Not yet a client? Sign-up here.
        </a>
    </p>
    <div class="tradetracker-header-actions">
        <a id="tradetracker-button_help" class="helpbutton"
           href="mailto:info.nl@tradetracker.com?subject=Magento 2 Extension Support Issue: "
           target="_blank">
            <i class="tradetracker-icon__question-circled"></i>
            <span><?= $block->escapeHtml(__('Support')); ?></span>
        </a>
        <a id="tradetracker-button_support" class="support"
           href="https://vimeo.com/552386282/90b3ac3f55"
           target="_blank">
            <i class="tradetracker-icon__envelop"></i>
            <span><?= $block->escapeHtml(__('Documentation')); ?></span>
        </a>
        <a id="tradetracker-button_register" class="register"
           href="https://merchant.tradetracker.com/webService"
           target="_blank" style="background: #ee3824;">
            <i class="tradetracker-icon__envelop"></i>
            <span><?= $block->escapeHtml(__('Login')); ?></span>
        </a>
    </div>
</div>
<br>
<div class="tradetracker-header-developed">
    <p style="background-image: url(<?= $block->escapeUrl($block->getImage()); ?>)"></p>
    <p>Developed in partnership with <a href="https://www.magmodules.eu/" target="_blank">Magmodules</a></p>
</div>
